services:
  db:
    image: postgres:15-alpine
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: quarkus-reactive-test
      POSTGRES_PASSWORD: quarkus-reactive-test
      POSTGRES_DB: db
      KTHCLOUD_VISIBILITY: private
      KTHCLOUD_CORES: 0.1
      KTHCLOUD_RAM: 0.1
    volumes:
      - data:/var/lib/postgres/data

volumes:
  data:
